production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: vmail
 pool: 5
 username: root
 password: root
 host: 127.0.0.0
 port: 3306
development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: vmail
 pool: 5
 username: root
 password: root
 host: localhost
 port: 3306